### ISSUE TITLE
hey your site is not complete . but looks good to me 

### ISSUE THREAD

**Issue by Prady2006** [geekysam7/Nexter-Project#1]
![Screenshot from 2020-04-08 23-57-17](https://user-images.githubusercontent.com/44490678/78820240-fb9bd200-79c6-11ea-95a8-f399917fcc2b.png)

**Comment by geekysam7** [comment]
Thanks for pointing out @Prady2006 . I will try to add JS to the project as it has been a long time pending.
As of now i am closing this issue.
